# Generated by Django 3.1.3 on 2020-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='', upload_to='pets'),
            preserve_default=False,
        ),
    ]
